name:                interp
version:             1.0.0.2
github:              "swizzard/interp"
license:             BSD3
author:              "sam raker"
maintainer:          "sam.raker@gmail.com"
copyright:           "(c) 2019 sam raker"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            Tracery-like randomized text interpolation
category:            Text, Interpolation

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/swizzard/interp#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- bytestring
- containers
- hspec
- megaparsec
- mtl
- optparse-applicative
- parser-combinators
- random-fu
- rvar
- semigroups
- text
- transformers
- unordered-containers
- vector

library:
  source-dirs: src

executables:
  interp:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - interp

tests:
  interp-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - interp
